### ISSUE TITLE
qsv -U says 2.1.0 but updates to 2.0.0

### ISSUE THREAD

**Issue by ondohotola** [dathere/qsv#2438]
I ran `qsv -U` on my Mac OS 15 15.2 ARM in the hope of looking whether the updated `pivotp` fixes my problem (#2425) and receive

```
Checking GitHub for updates...
Update 2.1.0 available. Current version is 1.0.0.
Release notes: https://github.com/dathere/qsv/releases/tag/2.1.0

[00:00:36] [========================================] 158.87 MiB/158.87 MiB (0s) Done                                                                Verifying downloaded file...
Update successful for qsv: `2.0.0`!
```

I will try again tonight but thought I let you know.

**Comment by jqnatividad** [comment]
It should work now @ondohotola . This is because it takes a while to build the various binary archives for the different platforms and until then, the latest version is staged in pre-release (from which you can download manually).

The good news is the self-update crate which qsv uses to power its self-update feature recently merged pre-release support (https://github.com/jaemk/self_update/pull/140). I'll add it to the backlog using this issue to track it.

This is a best practice anyway, and it  was spurred by https://github.com/dathere/qsv/issues/2350.

**Comment by ondohotola** [comment]
Thank you.

Unfortunately it still doesn't do the pivot like I want/need though #2425.
